site_name: CommandLine Basics
theme:
  name: material
  nav:
  - Home: index.md
  - Introduction: introduction.md
  - Basic Commands: basic-commands.md
  - File Operations:
      - Organize Files: organize-files.md
      - Search and Move Files: search-move-files.md
      - Deleting Files: deleting-files.md
  - Advanced Topics: 
      - Scripting: scripting.md
      - Custom Commands: custom-commands.md
  - Troubleshooting: troubleshooting.md
  - Glossary: glossary.md
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: deep purple
      accent: lime
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: deep purple
      accent: lime

  markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.arithmatex:
        generic: true
    - footnotes
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.mark
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    

